model:
  musicvae_name: fourth
  musicvae_path: "data/output/musicvae_finetune"
  melodyfixer_name: first
  melodyfixer_name: "data/output/melodyfixer_finetune"
generate:
  use_melodyfixer: true
  n_mask: 4
data:
  input_dir: "data/input/origin"
  output_dir: "data/output/final"
  backing_file: sample1_backing.mid
  chord_file: sample1_chord.csv
  submission_midi_file: output_sample1.mid
  full_midi_file: output_sample1_full.mid
  wav_file: final.wav
logger:
  level: "INFO"