model:
  musicvae_name: sixth
  musicvae_path: "data/output/musicvae_finetune"
  melodyfixer_name: second
  melodyfixer_path: "data/output/melodyfixer_finetune"
generate:
  use_melodyfixer: true
  n_mask: 4
data:
  input_dir: "data/input/demo"
  output_dir: "data/output/demo"
  backing_file: sample3_backing.mid
  chord_file: sample3_chord.csv
  submission_midi_file: output_sample3.mid
  full_midi_file: output_sample3_full.mid
  wav_file: final.wav
logger:
  level: "INFO"