services:
  benzaiten:
    build: .
    shm_size: '4gb'
    env_file: devcontainer.env
    volumes:
      - ../:/workspace:cached
    ports:
      - 8888:8888
    command: jupyter lab --port=8888 --ip=0.0.0.0 --allow-root --no-browser
    tty: true