services:
  benzaiten:
    build: .
    env_file: devcontainer.env
    volumes:
      - ../:/workspace:cached
    ports:
      - 8888:8888
    command: jupyter lab --port=8888 --ip=0.0.0.0 --allow-root --no-browser
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]